### ISSUE TITLE
Caused Bootloop: Android 11 A305F

### ISSUE THREAD

**Issue by aL1NaZ4R** [Xosrov/Android-Timezone-Fix#6]
My device stuck in boot animation. Fixed by removing the module via adb shell.

OS: SnakeOS Rebirth (Android 11, One UI 3.1)
Kernel: Eureka R13 (Update Jul 14, 2023)
Using Magisk 26.1

**Comment by Xosrov** [comment]
Thanks for bringing this to my attention. Most of the issues so far have been with android 11, so I'll be adding a disclaimer to dissuade users below android 12 from using this module until we can remedy the issue.

**Comment by rvneXe** [comment]
Cheers. But it has a small grammar issue, You should write "11 and below"
